version: "3.9"

services:

  iupp-nats-streaming:
    image: nats-streaming
    container_name: nats-streaming
    ports:
      - "14222:4222"
      - "18222:8222"
      - "16222:6222"
    command:
      - "--cluster_id=math-nats-streaming"
      - "--user=math-user"
      - "--pass=math-pass"
      - "-store=file"
      - "-dir=datastore"
    volumes:
      - nats:/datastore

volumes:
  nats: