micronaut:
  application:
    name: address
  server:
    port: 8082
endpoints:
  health:
    enabled: true
cassandra:
  default:
    basic:
      contact-points:
        - localhost:9042
      session-keyspace: address
      load-balancing-policy:
        local-datacenter: datacenter1
nats:
  addresses:
    - "nats://localhost:4222"

