micronaut:
  application:
    name: login
    server:
      port: 8080
endpoints:
  health:
    enabled: true
cassandra:
  default:
    basic:
      contact-points:
        - localhost:9042
      session-keyspace: login
      load-balancing-policy:
        local-datacenter: datacenter1
nats:
  addresses:
    - "nats://localhost:4222"